### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by easella** [LudicrousDevelopment/LudicrousOfficial#5]
![image](https://user-images.githubusercontent.com/74786054/115810008-2763dd00-a3bb-11eb-89e2-744892657080.png)
womginx and all the other proxies dont work either

**Comment by Nebelung-Dev** [comment]
wip

**Comment by s-tn** [comment]
Ludicrous.gq does not work with subdomains for some reason.

Use instead:
https://dairyfarms.ml
https://bestschools.gq

**Comment by easella** [comment]
they are both blocked

**Comment by s-tn** [comment]
They will most likely be blocked by your school, yes.

**Comment by sk8ordiechicago** [comment]
> they are both blocked

im working on making it so that you can deploy it on repl.it, heroku, and glitch

**Comment by Nebelung-Dev** [comment]
its not working because its looking for a proxy on a.yourwebsite.you.repl.co just deploy a new a new alloy proxy (or something else).  all the proxies on the site are not new and are on another subdomain
