### ISSUE TITLE
school blocking

### ISSUE THREAD

**Issue by easella** [LudicrousDevelopment/LudicrousOfficial#6]
please help
![image](https://user-images.githubusercontent.com/74786054/117679558-61d0c680-b17e-11eb-8a41-6de5e19e53f6.png)
![image](https://user-images.githubusercontent.com/74786054/117679635-7319d300-b17e-11eb-9526-d92ceef9e614.png)
i need a new link that is unblocked for contentkeeper

**Comment by sk8ordiechicago** [comment]
> please help
> ![image](https://user-images.githubusercontent.com/74786054/117679558-61d0c680-b17e-11eb-8a41-6de5e19e53f6.png)
> ![image](https://user-images.githubusercontent.com/74786054/117679635-7319d300-b17e-11eb-9526-d92ceef9e614.png)
> i need a new link that is unblocked for contentkeeper

Uhhh I'll get started on working out a way we can make it so that people can create their own links for it.

**Comment by nevr13** [comment]
i know im not part of development but please stop spamming issues, it's a little irritating. And make sure not to put sensitive info in images. :) @easella

**Comment by Nebelung-Dev** [comment]
this is not a new proxy just it is just alloy womginx voidnet and pydodge hosted on a subdomain. if you want those proxys go to there pages. you have made so many issues saying that the io games you want for your website are blocked. stop @easella 

yes i had to find these

https://github.com/hypothesis/via/issues/506
https://github.com/hypothesis/via/issues/497
https://github.com/titaniumnetwork-dev/alloy/issues/38
https://github.com/titaniumnetwork-dev/alloy/issues/37
https://github.com/ldbib/proxive/issues/2
https://github.com/ldbib/proxive/issues/1
https://github.com/luvuong-le/code-editor-tutorial/issues/1
https://github.com/webrecorder/wombat/issues/61
https://github.com/LudicrousDevelopment/LudicrousOfficial/issues/6
https://github.com/evennode/github-actions-deploy-to-evennode/issues/3
https://github.com/titaniumnetwork-dev/Molten/issues/8
https://github.com/davidebangelista/Goguardian-bypasser/issues/3
https://github.com/davidebangelista/Goguardian-bypasser/issues/2
https://github.com/charleywright/Kahoot-rocks-old/issues/13
https://github.com/charleywright/Kahoot-rocks-old/issues/12
https://github.com/LudicrousDevelopment/VoidNet/issues/4
https://github.com/LudicrousDevelopment/VoidNet/issues/2
https://github.com/sysce/proxy/issues/9
https://github.com/sysce/proxy/issues/8
https://github.com/titaniumnetwork-dev/Molten/issues/5
https://github.com/titaniumnetwork-dev/Molten/issues/4
https://github.com/gupta-shantanu/proxySite/issues/2
https://github.com/Monstars-dev/Goblin/issues/2
https://github.com/BinBashBanana/PyDodge/issues/13
https://github.com/BinBashBanana/PHP-Proxies/issues/1
https://github.com/vincentclee/glype/issues/3
https://github.com/titaniumnetwork-dev/alloy/issues/18
https://github.com/mse-k/shapez.io/issues/4

**Comment by nevr13** [comment]
preach
